Events.BroadcastRemote("ToggleNoclip", function (player)
    local character = player:GetControlledCharacter()
    Console.Log("Toggling flying mode for " .. player:GetName())
    character:SetFlyingMode(true)
end)